version: '3.1'
networks:
  app_network:
    driver: bridge

services:
  gameinterface:
    build: gameinterface
    volumes:
      - ./GameInterface:/app/GameInterface
    networks:
      - app_network
    command: npm start

  backend:
    build: server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - gameinterface
    command: npm run start:dev

  frontend:
    build: front
    ports:
      - "5100:5100"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend
      - gameinterface
    networks:
      - app_network
    command: npm run dev

