version: '3.1'
networks:
  app_network:
    name: fastnetwork
    driver: bridge

services:
  backend:
    build: server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network

  frontend:
    build: front
    ports:
      - "5100:5100"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app_network
