# Utilisez l'image Node.js en tant qu'image de base
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /app/GameInterface

# Copier les fichiers du GameInterface dans le conteneur
COPY . .

# Installer les dépendances
RUN npm install


