import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/assets/styles/index.scss";
import './index.css'
import styles from  "./body.module.scss"
import React from "react";
const inter = Inter({ subsets: ["latin"] });
import {UserContextProvider} from "../context/userContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.bodyContainer}`}>
        <UserContextProvider>
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
