import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/index.scss";
import styles from  "./body.module.scss"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.bodyContainer}`}>{children}</body>
    </html>
  );
}
